### ISSUE TITLE
Doesn't install with Node 0.12

### ISSUE THREAD

**Issue by schickling** [rauchg/clif#1]
Unfortunately I'm not able to install this tool with node 0.12 (installed via brew).

**Comment by veggiemonk** [comment]
Same here:
After <code>npm install -g clif</code>

``` javascript
module.js:338
    throw err;
          ^
Error: Cannot find module '../node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/clif/bin/clif:5:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```
